(ocamllex tr_lexer trg_lexer)
(menhir (modules tr_parser trg_parser))
(library
 (name trenchclib)
 (libraries str) 
 (modules
   programRep
   exceptions
   absyn
   field_props
   optimize
   tr_lexer
   tr_parser
   trg
   trg_lexer
   trg_parser
   themes
   features
   toProgramRep
   flags
   compile
   builtins
   builtins_modern
   resources
   helpers
 )
)